"""
Django settings for pycon_csp project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from django.utils.csp import CSP # Import CSP constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pfe$x#flu1yjps7d2@ktgol6tx)xa_4js6lga_i)3&+y(bkux+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog', # Register the app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware', # csp middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pycon_csp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csp', # exposes {{ csp_nonce }} in every template - used in Phase 3
            ],
        },
    },
]

WSGI_APPLICATION = 'pycon_csp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Logging - show CSP violation reports in terminal
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'csp': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}

# DEMO PHASES
CSP_PHASE = 3

# PHASE 0: No CSP
# The ContentSecurityPolicyMiddleware is present but sends no CSP header.
if CSP_PHASE == 0:
    pass

# PHASE 1: Report-Only
# The middleware sends Content-Security-Policy-Report-Only on every response.
# The browser logs violations but does NOT block anything - safe on live apps.
elif CSP_PHASE == 1:
    SECURE_CSP_REPORT_ONLY = {
        'default-src': [CSP.SELF],
        'script-src': [CSP.SELF],
        'style-src': [CSP.SELF],
        'img-src': [CSP.SELF, 'data:'],
        'report-uri': ['/csp-report/'], # violations posted here
    }

# PHASE 2: Enforce
# SECURE_CSP is Django 6.0's enforcement setting.
# The middleware sends Content-Security-Policy - browser BLOCKS violations.
elif CSP_PHASE == 2:
    SECURE_CSP = {
        'default-src': [CSP.SELF],
        'script-src': [CSP.SELF],
        'style-src': [CSP.SELF, 'https://cdn.jsdelivr.net'], #CDN whitelisted
        'img-src': [CSP.SELF, 'data:'],
        'font-src': [CSP.SELF],
        'connect-src': [CSP.SELF],
        'frame-ancestors': [CSP.NONE], # prevents clickjacking
        'base-uri': [CSP.SELF], #prevents base-tag injection
        'form-action': [CSP.SELF], # locks down form submissions
    }

# PHASE 3: Nonce
# CSP.NONCE in script-src tells Django to:
#   1. Generate a cryptographic random token per request.
#   2. Insert 'nonce-<token>' into the Content-Security-Policy header.
#   3. Expose the token as {{ csp_nonce }} via the context processor.
elif CSP_PHASE == 3:
    SECURE_CSP = {
        'default-src': [CSP.SELF],
        'script-src': [CSP.SELF, CSP.NONCE], # nonce enables {{ csp_nonce }}
        'style-src': [CSP.SELF, 'https://cdn.jsdelivr.net'],
        'img-src': [CSP.SELF, 'data:'],
        'font-src': [CSP.SELF],
        'connect-src': [CSP.SELF],
        'frame-ancestors': [CSP.NONE],
        'base-uri': [CSP.SELF],
        'form-action': [CSP.SELF],
    }